import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative min-h-screen bg-neutral-100 `}
      >
        <h2 className="text-center pt-16 pb-12 text-5xl font-serif">
          Survery Form
        </h2>
        <main className="flex flex-col items-center justify-between md:mx-auto mx-4 md:w-auto md:max-w-md card bg-white shadow-lg p-4 lg:p-8">
          {children}
        </main>
      </body>
    </html>
  );
}
